version: "2"
services:

  uwsgi:
    build: ./app
    volumes:
      - ./app:/var/www/
    expose:
      - "3031"
    environment:
      TZ: "Asia/Shanghai"
    privileged: true
  redis:
    image: "redis:alpine"

  nginx:
    build: ./nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    links:
      - uwsgi
    ports:
      - "8092:80"
    environment:
      TZ: "Asia/Shanghai"
    privileged: true